[versions]
gearyPaper = "0.31.3"

[libraries]
geary-papermc = { module = "com.mineinabyss:geary-papermc", version.ref = "gearyPaper" }
placeholderapi = "me.clip:placeholderapi:2.11.6"
huskhomes = "net.william278.huskhomes:huskhomes-bukkit:4.7"
