[versions]
gearyPaper = "0.30.1"

[libraries]
geary-papermc = { module = "com.mineinabyss:geary-papermc", version.ref = "gearyPaper" }
placeholderapi = "me.clip:placeholderapi:2.11.6"
huskhomes = "net.william278.huskhomes:huskhomes-bukkit:4.6.3"
